name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.21.3

      - name: Install dependencies
        run: npm install

      - name: Build the Vue.js application
        run: npm run build

      - name: Deploy to Plesk server
        uses: appleboy/scp-action@master
        with:
          host: 4help.tn
          username: a.chattaoui
          password: 5Vq4*r60w
          source: "dist/"
          target: "/var/www/vhosts/flyandferry.4help.tn/httpdocs/"